### ISSUE TITLE
TODO for the code

### ISSUE THREAD

**Issue by fastred** [macoscope/NotificationController#3]
- [x] replace assertions with returning the result of an operation
- [x] add comments to headers
- [x] add selector-based API
- [x] allow use without notification name
